### ISSUE TITLE
Create a Form in forms.py for Contact Details 

### ISSUE THREAD

**Issue by prafullpandey614** [prafullpandey614/HactoberFest-2022#13]
![Screenshot (334)](https://user-images.githubusercontent.com/81959129/193222419-6c04d179-45fd-4692-a7bd-74bb636c5ff3.png)

**Comment by BassCoder2808** [comment]
Hi @prafullpandey614, can I contribute to this issue? Can you assign this issue to me if it is still open

**Comment by aryaupadhyay24** [comment]
Hello I'm Arya Upadhyay, I want to work on this issue.

**Comment by prafullpandey614** [comment]
Hello @aryaupadhyay24 
Welcome to the Hactoberfest 
This issue is now resolved by @BassCoder2808 
But you can still contribute to this project by making another model in models.py it maybe for anything like Librarian or Staff Model
