### ISSUE TITLE
Add the url for about us page in Desk app's urls.py 

### ISSUE THREAD

**Issue by prafullpandey614** [prafullpandey614/HactoberFest-2022#14]
<img width="701" alt="30 09 2022_13 42 57_REC" src="https://user-images.githubusercontent.com/81959129/193224186-634aca85-189b-497a-a844-350e22e59261.png">

For further queries feel free to ask

**Comment by Shyamala7** [comment]
Can I take this?

**Comment by prafullpandey614** [comment]
@Shyamala7  Sure ! First add yourself in Contirbutors.md and make a PR 
and also don't forget to give this repository a star 
Happy Coding :)

**Comment by Raj-m01** [comment]
Hey, is this issue still open? I am interested to work on it.

**Comment by Shyamala7** [comment]
@prafullpandey614 Could you please check the [PR 29](https://github.com/prafullpandey614/HactoberFest-2022/pull/29) when you get some time

**Comment by prafullpandey614** [comment]
I checked it and Replied you there @Shyamala7
