### ISSUE TITLE
Add cursor pointer property in navbar list items using css 

### ISSUE THREAD

**Issue by prafullpandey614** [prafullpandey614/HactoberFest-2022#6]
<img width="955" alt="29 09 2022_11 02 32_REC" src="https://user-images.githubusercontent.com/81959129/192947015-db8efff6-7bd2-4efd-b66d-e6a8f3b139c8.png">

**Comment by AryanP45** [comment]
I`d like to do it!

**Comment by prafullpandey614** [comment]
@AryanP45  Sure and Welcome to hactoberfest !
You would make a PR in October as a part of hactoberfest
although I assigned this task to you
Give a star to this Repository and Add yourself in CONTRIBUTORS.md First

**Comment by prafullpandey614** [comment]
@AryanP45 You have to change the code in base.html which is present in root folder root/templates/base.html

Happy Coding !

**Comment by AryanP45** [comment]
> @AryanP45 Sure and Welcome to hactoberfest ! You would make a PR in October as a part of hactoberfest although I assigned this task to you Give a star to this Repository and Add yourself in CONTRIBUTORS.md First

Thanks Prafull :)

**Comment by avezqureshi14** [comment]
Hello @prafullpandey614  Sir before @AryanP45 I had made a Pull Request to this issue please check it out Sir

**Comment by AryanP45** [comment]
> Hello @prafullpandey614  Sir before @AryanP45 I had made a Pull Request to this issue please check it out Sir

This Repository is for Hacktoberfest, there's no point in making pull requests now @avezqureshi14 ,

**Comment by prafullpandey614** [comment]
@avezqureshi14  Sorry to say but I assigned this issue to @AryanP45 and you can contribute to something else in this repository and there are lot of things to do
